algoritmo "Bem-vindo, nome"
// Função : Programa para ler um nome e imprimir na tela: "Bem Vindo nome".
// Autor : Márcio Costa Brinck.
// Data : 16/03/2016

// Seção de Declarações 
var
nome_usuario :caractere

inicio
// Seção de Comandos
escreval("Olá usuário!")
escreva("Usuário, digite seu nome: ")
leia(nome_usuario)
escreval("Bem vindo, ", nome_usuario, ".")
escreval("Obrigado por utilizar o programa.")

fimalgoritmo
