algoritmo "Quadrado de um número"
// Função : Ler um numero e imprimir seu quadrado na tela.
// Autor :  Márcio Costa Brinck.
// Data : 16/03/2016

// Seção de Declarações
var
num :real

inicio
// Seção de Comandos
escreval("Olá usuário.")
escreval("Digite abaixo o número a ser elevado ao quadrado:")
leia(num)
escreval("_________________________________________________")
escreval("Resultado: ", num^2)
escreval("Obrigado por utilizar este programa!")

fimalgoritmo
